# Generated by Django 2.1.5 on 2019-01-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.CharField(blank=True, max_length=100)),
                ('home_team_name', models.CharField(blank=True, max_length=100)),
                ('home_team_goal', models.CharField(blank=True, max_length=100)),
                ('home_team_player_1_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_2_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_3_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_4_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_5_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_6_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_7_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_8_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_9_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_10_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_11_location', models.CharField(blank=True, max_length=100)),
                ('home_team_player_1_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_2_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_3_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_4_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_5_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_6_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_7_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_8_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_9_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_10_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_11_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_1_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_2_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_3_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_4_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_5_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_6_position', models.CharField(blank=True, max_length=100)),
                ('home_team_player_sub_7_position', models.CharField(blank=True, max_length=100)),
                ('home_team_defender_count', models.CharField(blank=True, max_length=100)),
                ('home_team_midfielder_count', models.CharField(blank=True, max_length=100)),
                ('home_team_foward_count', models.CharField(blank=True, max_length=100)),
                ('away_team_name', models.CharField(blank=True, max_length=100)),
                ('away_team_goal', models.CharField(blank=True, max_length=100)),
                ('away_team_player_1_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_2_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_3_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_4_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_5_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_6_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_7_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_8_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_9_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_10_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_11_location', models.CharField(blank=True, max_length=100)),
                ('away_team_player_1_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_2_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_3_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_4_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_5_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_6_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_7_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_8_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_9_position', models.CharField(blank=True, max_length=100)),
                ('away_team_player_10_position', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('player_nation', models.CharField(blank=True, max_length=100)),
                ('player_back_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_1', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_10', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_11', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_2', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_3', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_4', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_5', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_6', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_7', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_8', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_9', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_1', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_2', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_3', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_4', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_5', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_6', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_7', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_1', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_10', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_11', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_2', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_3', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_4', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_5', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_6', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_7', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_8', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_9', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_1', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_2', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_3', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_4', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_5', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_6', to='datacenter.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_player_sub_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_7', to='datacenter.Player'),
        ),
    ]
