# Generated by Django 2.1.5 on 2019-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='home_team_foward_count',
            new_name='home_team_forward_count',
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_defender_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_forward_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_midfielder_count',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
