# Generated by Django 2.1.5 on 2019-02-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_auto_20190201_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_team_player_10_location',
            new_name='away_team_player_11_position',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_11_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_1_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_2_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_3_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_4_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_5_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_6_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_7_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_8_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_player_9_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_10_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_11_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_1_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_2_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_3_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_4_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_5_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_6_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_7_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_8_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_player_9_location',
        ),
    ]
