# Generated by Django 2.1.5 on 2019-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_auto_20190201_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_1_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_2_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_3_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_4_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_5_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_6_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_player_sub_7_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
