# Generated by Django 2.1.5 on 2019-02-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0009_auto_20190201_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerNation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.PlayerName'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.PlayerNation'),
        ),
    ]
