# Generated by Django 2.1.5 on 2019-02-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_auto_20190202_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DateWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_name', to='datacenter.TeamName'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_10_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_10_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_11_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_11_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_1_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_1_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_2_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_2_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_3_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_3_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_4_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_4_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_5_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_5_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_6_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_6_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_7_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_7_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_8_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_8_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_9_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_9_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_1_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_1_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_2_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_2_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_3_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_3_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_4_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_4_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_5_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_5_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_6_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_6_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_player_sub_7_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_7_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_name', to='datacenter.TeamName'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_10_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_10_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_11_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_11_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_1_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_1_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_2_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_2_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_3_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_3_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_4_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_4_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_5_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_5_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_6_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_6_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_7_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_7_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_8_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_8_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_9_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_9_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_1_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_1_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_2_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_2_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_3_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_3_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_4_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_4_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_5_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_5_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_6_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_6_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_player_sub_7_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_7_position', to='datacenter.PlayerPosition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.DateMonth'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date_weekday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.DateWeekday'),
        ),
    ]
