# Generated by Django 2.1.5 on 2019-02-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0013_match201819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=100)),
                ('match_date_day', models.CharField(blank=True, max_length=100)),
                ('match_date_year', models.CharField(blank=True, max_length=100)),
                ('home_team_goal', models.CharField(blank=True, max_length=100)),
                ('home_team_line_1_count', models.CharField(blank=True, max_length=100)),
                ('home_team_line_2_count', models.CharField(blank=True, max_length=100)),
                ('home_team_line_3_count', models.CharField(blank=True, max_length=100)),
                ('home_team_line_4_count', models.CharField(blank=True, max_length=100)),
                ('home_team_line_5_count', models.CharField(blank=True, max_length=100)),
                ('home_team_line_6_count', models.CharField(blank=True, max_length=100)),
                ('away_team_goal', models.CharField(blank=True, max_length=100)),
                ('away_team_line_1_count', models.CharField(blank=True, max_length=100)),
                ('away_team_line_2_count', models.CharField(blank=True, max_length=100)),
                ('away_team_line_3_count', models.CharField(blank=True, max_length=100)),
                ('away_team_line_4_count', models.CharField(blank=True, max_length=100)),
                ('away_team_line_5_count', models.CharField(blank=True, max_length=100)),
                ('away_team_line_6_count', models.CharField(blank=True, max_length=100)),
                ('away_team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_name', to='datacenter.TeamName')),
                ('away_team_player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_1', to='datacenter.Player')),
                ('away_team_player_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_10', to='datacenter.Player')),
                ('away_team_player_10_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_10_position', to='datacenter.PlayerPosition')),
                ('away_team_player_11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_11', to='datacenter.Player')),
                ('away_team_player_11_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_11_position', to='datacenter.PlayerPosition')),
                ('away_team_player_1_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_1_position', to='datacenter.PlayerPosition')),
                ('away_team_player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_2', to='datacenter.Player')),
                ('away_team_player_2_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_2_position', to='datacenter.PlayerPosition')),
                ('away_team_player_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_3', to='datacenter.Player')),
                ('away_team_player_3_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_3_position', to='datacenter.PlayerPosition')),
                ('away_team_player_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_4', to='datacenter.Player')),
                ('away_team_player_4_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_4_position', to='datacenter.PlayerPosition')),
                ('away_team_player_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_5', to='datacenter.Player')),
                ('away_team_player_5_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_5_position', to='datacenter.PlayerPosition')),
                ('away_team_player_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_6', to='datacenter.Player')),
                ('away_team_player_6_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_6_position', to='datacenter.PlayerPosition')),
                ('away_team_player_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_7', to='datacenter.Player')),
                ('away_team_player_7_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_7_position', to='datacenter.PlayerPosition')),
                ('away_team_player_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_8', to='datacenter.Player')),
                ('away_team_player_8_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_8_position', to='datacenter.PlayerPosition')),
                ('away_team_player_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_9', to='datacenter.Player')),
                ('away_team_player_9_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_9_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_1', to='datacenter.Player')),
                ('away_team_player_sub_1_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_1_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_2', to='datacenter.Player')),
                ('away_team_player_sub_2_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_2_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_3', to='datacenter.Player')),
                ('away_team_player_sub_3_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_3_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_4', to='datacenter.Player')),
                ('away_team_player_sub_4_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_4_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_5', to='datacenter.Player')),
                ('away_team_player_sub_5_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_5_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_6', to='datacenter.Player')),
                ('away_team_player_sub_6_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_6_position', to='datacenter.PlayerPosition')),
                ('away_team_player_sub_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_7', to='datacenter.Player')),
                ('away_team_player_sub_7_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_player_sub_7_position', to='datacenter.PlayerPosition')),
                ('home_team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_name', to='datacenter.TeamName')),
                ('home_team_player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_1', to='datacenter.Player')),
                ('home_team_player_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_10', to='datacenter.Player')),
                ('home_team_player_10_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_10_position', to='datacenter.PlayerPosition')),
                ('home_team_player_11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_11', to='datacenter.Player')),
                ('home_team_player_11_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_11_position', to='datacenter.PlayerPosition')),
                ('home_team_player_1_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_1_position', to='datacenter.PlayerPosition')),
                ('home_team_player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_2', to='datacenter.Player')),
                ('home_team_player_2_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_2_position', to='datacenter.PlayerPosition')),
                ('home_team_player_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_3', to='datacenter.Player')),
                ('home_team_player_3_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_3_position', to='datacenter.PlayerPosition')),
                ('home_team_player_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_4', to='datacenter.Player')),
                ('home_team_player_4_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_4_position', to='datacenter.PlayerPosition')),
                ('home_team_player_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_5', to='datacenter.Player')),
                ('home_team_player_5_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_5_position', to='datacenter.PlayerPosition')),
                ('home_team_player_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_6', to='datacenter.Player')),
                ('home_team_player_6_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_6_position', to='datacenter.PlayerPosition')),
                ('home_team_player_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_7', to='datacenter.Player')),
                ('home_team_player_7_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_7_position', to='datacenter.PlayerPosition')),
                ('home_team_player_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_8', to='datacenter.Player')),
                ('home_team_player_8_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_8_position', to='datacenter.PlayerPosition')),
                ('home_team_player_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_9', to='datacenter.Player')),
                ('home_team_player_9_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_9_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_1', to='datacenter.Player')),
                ('home_team_player_sub_1_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_1_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_2', to='datacenter.Player')),
                ('home_team_player_sub_2_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_2_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_3', to='datacenter.Player')),
                ('home_team_player_sub_3_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_3_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_4', to='datacenter.Player')),
                ('home_team_player_sub_4_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_4_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_5', to='datacenter.Player')),
                ('home_team_player_sub_5_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_5_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_6', to='datacenter.Player')),
                ('home_team_player_sub_6_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_6_position', to='datacenter.PlayerPosition')),
                ('home_team_player_sub_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_7', to='datacenter.Player')),
                ('home_team_player_sub_7_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_player_sub_7_position', to='datacenter.PlayerPosition')),
                ('match_date_month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.DateMonth')),
                ('match_date_weekday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacenter.DateWeekday')),
            ],
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_1',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_10',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_10_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_11',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_11_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_1_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_2',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_2_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_3',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_3_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_4',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_4_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_5',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_5_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_6',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_6_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_7',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_7_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_8',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_8_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_9',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_9_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_1',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_1_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_2',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_2_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_3',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_3_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_4',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_4_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_5',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_5_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_6',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_6_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_7',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='away_team_player_sub_7_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_name',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_1',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_10',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_10_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_11',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_11_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_1_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_2',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_2_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_3',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_3_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_4',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_4_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_5',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_5_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_6',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_6_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_7',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_7_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_8',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_8_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_9',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_9_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_1',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_1_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_2',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_2_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_3',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_3_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_4',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_4_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_5',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_5_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_6',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_6_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_7',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='home_team_player_sub_7_position',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='match_date_month',
        ),
        migrations.RemoveField(
            model_name='match201819',
            name='match_date_weekday',
        ),
        migrations.DeleteModel(
            name='Match201819',
        ),
    ]
